config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :users do
    resources :images, only: [:create, :destroy]
  end

  resources :ingredients, except: [:new] do
    resources :images, only: [:create, :destroy]
  end

  resources :nutritional_infos, only: [:create, :destroy]
  resources :derived_measurements, only: [:create, :destroy]

  resources :recipes
  resources :subscriptions
  resources :images,        only: [:create, :destroy]
  get    '/login',   to: 'sessions#new'
  get    '/licenses',   to: 'licenses#index'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #get    '/logout',   to: 'sessions#destroy'
  #delete '/logout_all',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :nutritional_infos, presence: true
  validates :name, presence: true, length: { maximum: 15 }

  belongs_to :added_by, class_name: 'User'
  has_many :nutritional_infos, dependent: :destroy
  has_many :recipe_steps, dependent: :destroy

  has_many :ingredient_countries, dependent: :destroy
  has_many :countries, :through => :ingredient_countries

  has_many :report_cases, as: :reported, dependent: :destroy
  has_many :images, as: :depicted, dependent: :destroy
  accepts_nested_attributes_for :nutritional_infos
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @existingIngredient = Ingredient.find_by(name: @ingredient.name)
    if @existingIngredient && @existingIngredient.countries.include?(current_user.country)
        flash[:info] = 'Ingredient already exists'
        redirect_back_or ingredients_path
    else
        @ingredient.added_by = current_user
        @ingredient.countries << current_user.country
        @ingredient.nutritional_infos.each do |nutritional_info|
            nutritional_info.added_by = current_user
        end
        if @ingredient.save
            flash[:success] = 'Ingredient was added'
            redirect_back_or ingredients_path
        else
            flash[:danger] = 'Ingredient wasn\'t added'
            redirect_back_or ingredients_path
        end
    end
  end

  def show
    @ingredient = Ingredient.find(params[:id])
    @derived_measurement = @ingredient.nutritional_infos.first.derived_measurements.build
  end

  def index
    @ingredients = Ingredient.all
  end
  private
  def ingredient_params
    params.require(:ingredient).permit(:name, nutritional_infos_attributes: [:amount, :unit, :kcal, :protein, :carbohydrates, :fat, :saturates, :alcohol, :sugar, :salt, :fibre, :price])
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_ingredient_form.html.erb
<%= form_for ingredient = Ingredient.new do |user_form| %>
      <%= render 'shared/error_messages', object: user_form.object %>
      <%= user_form.label :name %> <%= user_form.text_field :name %>
      <%= user_form.fields_for :nutritional_infos, ingredient.nutritional_infos.build do |g| %>
          <%= render 'shared/error_messages', object: g.object %>
          <%= render 'nutritional_infos/nutritional_info_fields', f: g %>
      <% end %>
      <%= user_form.submit %>
<% end %>

app/views/ingredients/_ingredient_list_item.html.erb
<span class = 'ingredient_list_item'>
    <div id= ingredient_content>
        <span>
            <span id = 'ingredient_title'>
                <%= link_to ingredient_list_item.name, ingredient_path(ingredient_list_item) %>
            </span>
            <span id = 'nutritional_info'>
                <%= ingredient_list_item.nutritional_infos.first.kcal %> kcal / 100<%= ingredient_list_item.nutritional_infos.first.unit %>
                Protein: <%= ingredient_list_item.nutritional_infos.first.protein %>

                Carbohydrates: <%= ingredient_list_item.nutritional_infos.first.carbohydrates %>
                (Sugar: <%= ingredient_list_item.nutritional_infos.first.sugar %>)
                Fat: <%= ingredient_list_item.nutritional_infos.first.fat %>  
                (Saturates:<%= ingredient_list_item.nutritional_infos.first.saturates %>)
                Salt: <%= ingredient_list_item.nutritional_infos.first.salt %>
                <% if ingredient_list_item.nutritional_infos.first.fibre%>
                    Fibre: <%= ingredient_list_item.nutritional_infos.first.fibre %>
                <% end %>
                <% if ingredient_list_item.nutritional_infos.first.alcohol%>
                    Alcohol: <%= ingredient_list_item.nutritional_infos.first.alcohol %>
                <% end %>
            </span>
        </span>
    </div>

    <div class="ingredient_image_micro">
        <% if (ingImg = ingredient_list_item.images.order(:rating).first) %>
            <%= image_tag ingImg.path_url(:micro).to_s %>
        <% end %>
    </div>
</span>

app/views/ingredients/index.html.erb
<%= render partial: 'ingredients/ingredient_list_item', collection: @ingredients.order(:name) %>
<% if logged_in? %>
    <button id="add-button">+</button>
    <%= render 'ingredients/ingredient_form' %>
<% end%>

app/views/ingredients/show.html.erb
<%= @ingredient.name %>
<p>
</p>
<div id = "submit_image"> <%= render partial: 'images/image_form', locals: {depicted: @ingredient, image: @ingredient.images.build} %> </div>
<% @ingredient.images.order(:rating).each do |image| %>
    <%= image_tag image.path_url.to_s %>
<% end %>

<%= render partial: 'derived_measurements/derived_measurement_form' %>